steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ["build", "-t", "gcr.io/ultra-bearing-264000/gke-node", "."]
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/ultra-bearing-264000/gke-node"]
    - name: 'gcr.io/cloud-builders/gke-deploy:stable'
      args:
      - run
      - --image=gcr.io/ultra-bearing-264000/gke-node
      - --location=asia-northeast1-a
      - --cluster=nodejs-cluster
apiVersion: "v1"
kind: "Service"
metadata:
    name: "gke-node-service"
    namespace: "default"
    labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
    ports:
    - protocol: "TCP"
    port: 8080
    targetPort: 8080
    selector:
    app: "gke-node"
    type: "LoadBalancer"
    loadBalancerIP: ""
